@extends('layouts.main_page')
@section('title', 'Terms & Conditions')
@section('app_section', 'VirtualHub')
@section('logo', 'vhw')


@php


    @endphp

@section('content')
    <div class="terms">

        <div>
            <h1>Terms & Conditions</h1>
            <p lastupdate>Effective date: June 21, 2019</p>
        </div>

        <div>
            <p>Phenolix LTD ("us", "we", or "our") operates the https://vh-net.com/ website and the
                VirtualHub (available for iOS, Android and Web) application (hereinafter referred to as the "Service").</p>

            <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when
                you
                use our Service and the choices you have associated with that data.
            </p>

            <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection
                and
                use of information in accordance with this policy. Unless otherwise defined in this Terms and Conditions, the
                terms used in this Terms and Conditions have the same meanings as in our Terms and Conditions.</p>
        </div>

        <div>
            <h2>Definitions</h2>
            <ul>
                <li>
                    <p bold>Service</p>
                    <p>Service means the https://vh-net.com/ website and the VirtualHub iOS, Android and Net mobile
                        application operated by VirtualHub iOS, Android and Net</p>
                </li>
                <li>
                    <p bold>Personal Data</p>
                    <p>Personal Data means data about a living individual who can be identified from those data (or from
                        those and other information either in our possession or likely to come into our possession).</p>
                </li>
                <li>
                    <p bold>Usage Data</p>
                    <p>Usage Data is data collected automatically either generated by the use of the Service or from the
                        Service infrastructure itself (for example, the duration of a page visit).</p>
                </li>
                <li>
                    <p bold>Cookies</p>
                    <p>Cookies are small files stored on your device (computer or mobile device).</p>
                </li>
            </ul>
        </div>

        <div>
            <h2>Information Collection and Use</h2>
            <p>We collect several different types of information for various purposes to provide and improve our Service
                to
                you.</p>
            <br>
            <div>
                <h3>Types of Data Collected</h3>
                <br>
                <div>
                    <h4>Personal Data</h4>
                    <p>While using our Service, we may ask you to provide us with certain personally identifiable
                        information that
                        can be used to contact or identify you ("Personal Data"). Personally identifiable information
                        may include,
                        but is not limited to:</p>

                    <ul>
                        <li>Cookies and Usage Data</li>
                    </ul>
                </div>

                <div>
                    <h4>Usage Data</h4>

                    <p>We may also collect information that your browser sends whenever you visit our Service or when
                        you access the
                        Service by or through a mobile device ("Usage Data").</p>
                    <p>This Usage Data may include information such as your computer's Internet Protocol address (e.g.
                        IP address),
                        browser type, browser version, the pages of our Service that you visit, the time and date of
                        your visit, the
                        time spent on those pages, unique device identifiers and other diagnostic data.</p>
                    <p>When you access the Service by or through a mobile device, this Usage Data may include
                        information such as
                        the type of mobile device you use, your mobile device unique ID, the IP address of your mobile
                        device, your
                        mobile operating system, the type of mobile Internet browser you use, unique device identifiers
                        and other
                        diagnostic data.</p>
                </div>

                <div>
                    <h4>Tracking & Cookies Data</h4>
                    <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold
                        certain
                        information.</p>
                    <p>Cookies are files with a small amount of data which may include an anonymous unique identifier.
                        Cookies are
                        sent to your browser from a website and stored on your device. Other tracking technologies are
                        also used
                        such as beacons, tags and scripts to collect and track information and to improve and analyse
                        our
                        Service.</p>
                    <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.
                        However, if
                        you do not accept cookies, you may not be able to use some portions of our Service.</p>
                    <p>Examples of Cookies we use:</p>
                    <ul>
                        <li><p bold>Session Cookies.</p> We use Session Cookies to operate our Service.</li>
                        <li><p bold>Preference Cookies.</p> We use Preference Cookies to remember your preferences
                            and various
                            settings.
                        </li>
                        <li><p bold>Security Cookies.</p> We use Security Cookies for security purposes.</li>
                    </ul>
                </div>
            </div>
        </div>

        <div>
            <h2>Use of Data</h2>

            <p>VirtualHub iOS, Android and Net uses the collected data for various purposes:</p>
            <ul>
                <li>To provide and maintain the Service</li>
                <li>To notify you about changes to our Service</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                <li>To provide customer care and support</li>
                <li>To provide analysis or valuable information so that we can improve the Service</li>
                <li>To monitor the usage of the Service</li>
                <li>To detect, prevent and address technical issues</li>
            </ul>
        </div>

        <div>
            <h2>Transfer Of Data</h2>
            <p>Your information, including Personal Data, may be transferred to - and maintained on - computers located
                outside of your state, province, country or other governmental jurisdiction where the data protection
                laws
                may differ than those from your jurisdiction.</p>
            <p>If you are located outside United Kingdom and choose to provide information to us, please note that we
                transfer the data, including Personal Data, to United Kingdom and process it there.</p>
            <p>Your consent to this Terms and Conditions followed by your submission of such information represents your
                agreement
                to that transfer.</p>
            <p>VirtualHub iOS, Android and Net will take all steps reasonably necessary to ensure that your data is
                treated
                securely and in accordance with this Terms and Conditions and no transfer of your Personal Data will take
                place to
                an organization or a country unless there are adequate controls in place including the security of your
                data
                and other personal information.</p>
        </div>

        <div>
            <h2>Disclosure Of Data</h2>
            <br>
            <div>
                <h3>Legal Requirements</h3>
                <p>VirtualHub iOS, Android and Net may disclose your Personal Data in the good faith belief that such
                    action is
                    necessary to:</p>
                <ul>
                    <li>To comply with a legal obligation</li>
                    <li>To protect and defend the rights or property of VirtualHub iOS, Android and Net</li>
                    <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                    <li>To protect the personal safety of users of the Service or the public</li>
                    <li>To protect against legal liability</li>
                </ul>
            </div>
        </div>

        <div>
            <h2>Security of Data</h2>
            <p>The security of your data is important to us but remember that no method of transmission over the
                Internet or
                method of electronic storage is 100% secure. While we strive to use commercially acceptable means to
                protect
                your Personal Data, we cannot guarantee its absolute security.</p>
        </div>

        <div>
            <h2>Service Providers</h2>
            <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to
                provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how
                our
                Service is used.</p>
            <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are
                obligated not to disclose or use it for any other purpose.</p>

            <p>Our Service allows you to get access to various information that are courtesy of <span bold=""><a
                        href="https://www.mapbox.com/tos/">Mapbox, Inc</a></span>, <span bold=""><a
                        href="https://avwx.rest">AVWX.rest</a></span>, <span bold=""><a
                        href="https://airportediting.com">Infinite Flight Airport Editing</a></span> and <span
                    bold=""><a
                        href="https://www.aviationapi.com">AviationAPI</a></span> respectively. Phenolix or
                VirtualHub does NOT
                take full
                credit of these services.</p>

            <p>Phenolix owned charts (Containing "<span bold="">Custom</span>") are copyright.</p>
            <br>
            <div>
                <h3>Analytics</h3>
                <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
                <ul>
                    <li>
                        <p bold>Firebase Analytics</p>
                        <p>Firebase Analytics is a analytics service. You can visit their Terms and Conditions page here: <a
                                href="https://firebase.google.com/policies/analytics">Firebase Analytics</a>
                        </p>
                    </li>
                    <li>
                        <p bold>AdMob and AdSense</p>
                        <p>AdMob and AdSense is a advertisement service. You can visit their Terms and Conditions page here:
                            <a
                                href="https://support.google.com/admob/answer/6128543">AdMob & AdSense</a>
                        </p>
                    </li>

                    <li>
                        <p bold>Google Play Services, Fabric, and Crashlytics</p>
                        <p>You can visit their Terms and Conditions page here: <a
                                href="https://www.google.com/policies/privacy/">Google Play Services, Fabric, and Crashlytics</a>
                        </p>
                    </li>
                </ul>
            </div>

            <div>
                <h3>Third Party Cookies</h3>

                <p>In some special cases we also use cookies provided by trusted third parties. The following section
                    details
                    which third party cookies you might encounter through this site.</p>

                <ul>

                    <li>
                        <p>This site uses Google Analytics which is one of the most widespread and trusted analytics
                            solution on
                            the web for helping us to understand how you use the site and ways that we can improve your
                            experience. These cookies may track things such as how long you spend on the site and the
                            pages that
                            you visit so we can continue to produce engaging content.</p>
                        <p>For more information on Google Analytics cookies, see the official Google Analytics page.</p>
                    </li>

                    <li>
                        <p>Third party analytics are used to track and measure usage of this site so that we can
                            continue to
                            produce engaging content. These cookies may track things such as how long you spend on the
                            site or
                            pages you visit which helps us to understand how we can improve the site for you.</p>
                    </li>


                    <li>
                        <p>The Google AdSense service we use to serve advertising uses a DoubleClick cookie to serve
                            more
                            relevant ads across the web and limit the number of times that a given ad is shown to
                            you.</p>
                        <p>For more information on Google AdSense see the official Google AdSense privacy FAQ.</p>
                    </li>

                    <li>
                        <p>We use adverts to offset the costs of running this site and provide funding for further
                            development.
                            The behavioural advertising cookies used by this site are designed to ensure that we provide
                            you
                            with the most relevant adverts where possible by anonymously tracking your interests and
                            presenting
                            similar things that may be of interest.</p>
                    </li>


                    <li>
                        <p>We also use social media buttons and/or plugins on this site that allow you to connect with
                            your
                            social network in various ways. For these to work the following social media sites
                            including; Instagram and Twitter, will set cookies
                            through
                            our site which may be used to enhance your profile on their site or contribute to the data
                            they hold
                            for various purposes outlined in their respective privacy policies.</p>
                    </li>

                </ul>
            </div>
        </div>

        <div>
            <h2>Links to Other Sites</h2>
            <p>Our Service may contain links to other sites that are not operated by us. If you click a third party
                link,
                you will be directed to that third party's site. We strongly advise you to review the Terms and Conditions of
                every site you visit.</p>
            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of
                any
                third party sites or services.</p>
        </div>

        <div>
            <h2>Changes to This Terms and Conditions</h2>
            <p>We may update our Terms and Conditions from time to time. We will notify you of any changes by posting the new
                Terms and Conditions on this page.</p>
            <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming
                effective and update the "effective date" at the top of this Terms and Conditions.</p>
            <p>You are advised to review this Terms and Conditions periodically for any changes. Changes to this Privacy
                Policy
                are effective when they are posted on this page.</p>
        </div>

        <div>
            <h2>Contact Us</h2>
            <p>If you have any questions about this Terms and Conditions, please contact us:</p>
            <ul>
                <li>By email: contact@vh-net.com</li>
            </ul>
        </div>
    </div>
@endsection
